config/routes.rb
Rails.application.routes.draw do

  get "/home", to: "static_pages#home"
  get "/about", to: "static_pages#about"
  get "/index", to: "static_pages#index"
  root "static_pages#home"

  devise_for :users, controllers: {omniauth_callbacks: "omniauth_callbacks"}
  devise_scope :user do
    match "/sessions/user", to: "devise/sessions#create", via: :post
  end
  resources :category, only: [:index, :show] do
    resources :products, only: [:index, :show]
  end
  resources :products do
    resources :comments
  end
  namespace :admin do
    resources :users
    resources :orders
    resources :categories do
      resources :products do
        collection{post :import}
      end
    end
    resources :statistics, only: [:index]
    resources :suggest_products
  end
  resources :sessions, only: [:index, :create, :update, :destroy]
  resources :view, only: [:index]
  namespace :users do
    resources :orders, only: [:index, :create, :show]
  end
  resources :ratings, only: [:create, :update]
  resources :suggestions
  get "*path", to: "static_pages#home"
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @products = Product.take_home_product
  end

  def about
  end

  def index
    @products = Product.search_home params[:search]
    @products = Kaminari.paginate_array(@products)
      .page(params[:page]).per Settings.product.per_page_home
  end
end

app/views/static_pages/about.html.erb
<div class="container">
  <h1><%= t :FECO %></h1>
</div>

app/views/static_pages/home.html.erb
<div class="container">
  <div id="myCarousel" class="carousel slide" data-ride="carousel">
    <ol class="carousel-indicators">
      <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
      <li data-target="#myCarousel" data-slide-to="1"></li>
      <li data-target="#myCarousel" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner" role="listbox">
      <div class="item active">
        <%= link_to image_tag("0.png", class: "carousel-image"), root_path %>
      </div>
      <div class="item">
        <%= link_to image_tag("1.png", class: "carousel-image"), root_path %>
      </div>
      <div class="item">
        <%= link_to image_tag("2.png", class: "carousel-image"), root_path %>
      </div>
    </div>
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
      <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
      <span class="sr-only"><%= t :previous %></span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
      <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
      <span class="sr-only"><%= t :next %></span>
    </a>
  </div>
</div>
<div class="container">
  <div class="container text-center product-border">
    <h3><%= t :hot %></h3>
    <div class="row">
      <% @products.each_with_index do |product, index| %>
        <div class="col-sm-4">
          <p><strong><%= product.name %></strong></p>
          <div><%= picture_for product %></div>
          <button type="button" class="btn btn-info" data-toggle="collapse"
            data-target="#<%= product.id %>"><%= t :price %>
          </button>
          <div id="<%= product.id %>" class="collapse">
            <p class="price-product">
              <%= product.price %><i class="fa fa-dollar size-icon"></i>
            </p>
            <%= link_to t(:want_more_detail), category_product_path(
              category_id: product.category_id, id: product.id) %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/static_pages/index.html.erb
<div class="container">
  <div class="row">
    <% @products.each do |product| %>
      <div class="col-md-2 random-width">
        <%= link_to picture_for(product),
          category_product_path(category_id: product.category_id,
          id: product.id) %>
        <p class="name-product"><%= product.name %></p>
        <p class="price-product"><%= product.price %>
          <i class="fa fa-dollar size-icon"></i>
        </p>
      </div>
    <% end %>
    <div class="text-center"><%= paginate @products %></div>
  </div>
</div>