config/routes.rb
Rails.application.routes.draw do

  get "/home", to: "static_pages#home"
  get "/about", to: "static_pages#about"
  get "/index", to: "static_pages#index"
  root "static_pages#home"

  devise_for :users, controllers: {omniauth_callbacks: "omniauth_callbacks"}
  devise_scope :user do
    match "/sessions/user", to: "devise/sessions#create", via: :post
  end
  resources :category, only: [:index, :show] do
    resources :products, only: [:index, :show]
  end
  resources :products do
    resources :comments
  end
  namespace :admin do
    resources :users
    resources :orders
    resources :categories do
      resources :products do
        collection{post :import}
      end
    end
    resources :statistics, only: [:index]
    resources :suggest_products
  end
  resources :sessions, only: [:index, :create, :update, :destroy]
  resources :view, only: [:index]
  namespace :users do
    resources :orders, only: [:index, :create, :show]
  end
  resources :ratings, only: [:create, :update]
  resources :suggestions
  get "*path", to: "static_pages#home"
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  has_many :order_details, dependent: :destroy
  enum status: [:wait, :success, :delay]
  before_update :check_product_quantity_before_update
  ransacker :status, formatter: proc {|v| statuses[v]}

  class << self
    def load_info_to_chatwork order
      info = ""
      order.order_details.each do |order_detail|
        price = order_detail.product.price * order_detail.quantity
        info += "#{order_detail.product.name} #{order_detail.quantity} #{price}$\n"
      end
      info += "#{I18n.t(:total_price)} #{order.total_price}"
      return info
    end
  end

  private
  def check_product_quantity_before_update
    if status == Settings.success
      order_details.each do |order_detail|
        if order_detail.check_product_quantity
          throw :abort
        end
      end
      order_details.each do |order_detail|
        order_detail.update_product_quantity
      end
    end
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  load_and_authorize_resource
  before_action :verify_admin, :authenticate_user!

  def index
    params[:limit] = Settings.user.per_page
    @search = Order.search params[:q]
    @orders = @search.result.page(params[:page]).per params[:limit]
  end

  def edit
    @order_details = @order.order_details
    @products = get_product @order_details
    respond_to do |format|
      format.html{render partial: "list_order", locals: {order: @order,
        products: @products, order_details: @order_details}}
    end
  end

  def update
    if params[:status].present?
      unless params[:status] == Settings.success
        if @order.update_attributes status: params[:status]
          flash[:success] = t :update_success
        else
          flash[:notice] = t :update_fail
        end
      else
        if @order.update_attributes status: :success
          user = User.find_by id: @order.user_id
          SendOrderMailer.send_order(user, @order).deliver_now
          message_body = Order.load_info_to_chatwork @order
          ChatWork::Message.create room_id: ENV["chatwork_room_id"],
            body: message_body
          flash[:success] = t :success_order
        else
          @order.update_attributes status: :delay
          flash[:notice] = t :not_enough_product_in_stock
        end
      end
    end
    redirect_to admin_orders_path
  end

  private
  def get_product order_details
    products = []
    order_details.each do |order_detail|
      products.push(order_detail.product)
    end
    return products
  end
end

app/controllers/users/orders_controller.rb
class Users::OrdersController < ApplicationController
  before_action :check_current_user

  def index
    @orders = current_user.orders.order :created_at
    @orders = Kaminari.paginate_array(@orders)
      .page(params[:page]).per Settings.order.per_page
    @total_price = current_user.orders.sum :total_price
  end

  def create
    @products = Product.load_product_by_id " ", session[:cart]
    order = current_user.orders.create total_price: session[:total_price],
      status: Settings.order.new
    @products.each do |product|
      order.order_details.create quantity: session[product.id],
        product_id: product.id
    end
    session[:cart] = nil
    session[:total_price] = nil
    flash[:success] = t :order_successfully
    redirect_to root_path
  end

  def show
    @order = Order.find_by id: params[:id]
    order_details = OrderDetail.select{|x| x.order_id == @order.id}
    @product_quantity = Array.new
    order_details.each do |order|
      product = Product.find_by id: order.product_id
      @product_quantity.append [product, order.quantity]
    end
  end

  private

  def check_current_user
    if !current_user.present? || current_user.admin?
      flash[:warning] = t :login_please_as_user
      redirect_to root_path
    end
  end
end

app/views/admin/orders/_list_order.html.erb
<div class="container-fluid">
  <b><%= t :order_id %><%= @order.id %></b>
  <% unless order.status == "success" %>
    <%= form_tag admin_order_path(order), method: :put do %>  
      <div class="col-md-4 row">
        <%= t :status %>
        <%= select_tag :status, options_for_select(Order.statuses.keys,
          order.status.to_s)%>
      </div>
      <div class="col-md-3 row">
        <%= submit_tag t(:update), class: "btn btn-primary" %>
      </div>
    <% end %>
  <% end %>
  <table class="table">
    <tr>
      <td><%= t :product %></td>
      <td><%= t :quatity %></td>
      <td><%= t :in_stock %></td>
      <% unless order.status == "success" %>
        <td><%= t :enough_to_sell %>
      <% end %>
    </tr>
    <% @order_details.each_with_index do |order_detail, id| %>
      <tr>
        <td><%= get_product(products, id).name %></td>
        <td><%= order_detail.quantity %></td>
        <td><%= get_product(products, id).in_stock %></td>
        <% unless order.status == "success" %>
          <td>
            <% if order_detail.quantity < 
              get_product(products, id).in_stock %>
              <i class="glyphicon glyphicon-ok"></i>
            <% else %>
              <i class="glyphicon glyphicon-remove"></i>
            <% end %>
          </td>
        <% end %>
      </tr>
    <% end %>
  </table>
</div>

app/views/admin/orders/_order.html.erb
<tr>
  <td>
    <%= index_for order_counter, @orders.current_page,
      params[:limit] %>
  </td>
  <td><%= order.total_price %></td>
  <td>
    <% unless order.status == "success" %>
      <%= form_tag admin_order_path(order), method: :put do %>  
        <div class="col-md-8 row">
          <%= select_tag :status, options_for_select(Order.statuses.keys, order.status.to_s)%>
        </div>
        <div class="col-md-3 row">
          <%= submit_tag t(:update), class: "btn btn-primary" %>
        </div>
      <% end %>
    <% else %>
      <div class="col-md-3 pull-left">
        <%= t :success %>
      </div>
    <% end %>
  </td>
  <td><%= order.created_at.strftime("%H:%M:%S %d/%m/%Y") %>
  <td>
    <%= link_to edit_admin_order_path(order),
      class: "button-edit-order" do %>
      <span class="glyphicon glyphicon-pencil"></span>
    <% end %>
  </td>
</tr>

app/views/admin/orders/index.html.erb
<% provide :title, t(:orders) %>
<div class="container-fluid">
  <div class="col-md-offset-1">
    <h3><%= t :orders %></h3>
    <div class="search-form row">
      <%= search_form_for [:admin, @search], class: "form-inline" do |f| %>
        <div class="col-md-3">
          <div class="form-group">
            <%= f.label :status_cont, t(:search) %>
            <%= f.text_field :status_cont, class: "form-control" %>
          </div>
        </div>
        <div class= "col-md-2" >
          <%= f.submit t(:search),
            class: "btn btn-primary" %>
        </div>
      <% end %>
    </div>
  </div>
  <div class="col-md-9 col-md-offset-1">
    <table class="table table-bordered table-hover text-center">
      <tr>
        <th class="text-center col-md-1"><%= t :index %></th>
        <th class="text-center col-md-1"><%= t :total_price %></th>
        <th class="text-center col-md-2"><%= t :status %></th>
        <th class="text-center col-md-2"><%= t :order_date %></th>
        <th class="text-center col-md-1"><%= t :edit %></th>
      </tr>
      <tr>
        <%= render @orders %>
      </tr>
    </table>
    <%= paginate @orders, theme: "twitter-bootstrap-3" %>
  </div>
</div>
<div class="modal order-modal-edit">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="submit" class="close" data-dismiss="modal">
          &times;
        </button>
        <h3><%= t :edit_order %></h3>
      </div>
      <div class="modal-body-order-edit">

      </div>
    </div>
  </div>
</div>