config/routes.rb
Rails.application.routes.draw do

  get "/home", to: "static_pages#home"
  get "/about", to: "static_pages#about"
  get "/index", to: "static_pages#index"
  root "static_pages#home"

  devise_for :users, controllers: {omniauth_callbacks: "omniauth_callbacks"}
  devise_scope :user do
    match "/sessions/user", to: "devise/sessions#create", via: :post
  end
  resources :category, only: [:index, :show] do
    resources :products, only: [:index, :show]
  end
  resources :products do
    resources :comments
  end
  namespace :admin do
    resources :users
    resources :orders
    resources :categories do
      resources :products do
        collection{post :import}
      end
    end
    resources :statistics, only: [:index]
    resources :suggest_products
  end
  resources :sessions, only: [:index, :create, :update, :destroy]
  resources :view, only: [:index]
  namespace :users do
    resources :orders, only: [:index, :create, :show]
  end
  resources :ratings, only: [:create, :update]
  resources :suggestions
  get "*path", to: "static_pages#home"
end

app/controllers/admin/statistics_controller.rb
class Admin::StatisticsController < ApplicationController
  before_action :verify_admin, :authenticate_user!

  def index
    month_start = Time.new Time.now.year, Time.now.mon
    orders = OrderDetail.load_orders_by_month month_start
    @products = Product.load_product_by_order orders
    respond_to do |format|
      format.html
      format.xls
    end
    @data = Array.new
    @products.each do |product, quantity|
      @data.append [product.name, quantity]
    end
    StatisticsWorker.perform_at load_time
    @products = Kaminari.paginate_array(@products).page(params[:page])
      .per Settings.product.per_page
  end

  private

  def load_time
    year = Time.now.year
    month = Time.now.mon
    day = Time.days_in_month month, year
    Time.new year, month, day
  end
end

app/views/admin/statistics/index.html.erb
<div class="container">
  <div id="hcontainer" data-chart="<%= @data %>"></div>
</div>
<div class="container product-border">
  <div class="pull-right">
    <button class="btn btn-warning">
      <%= link_to t(:download_excel), admin_statistics_url(format: "xls"), id: "word-li" %>
    </button>
  </div>
  <div class="table-responsive padding-table">
    <table class="table table-width">
      <thead>
        <tr>
          <th><%= t :image %></th>
          <th><%= t :name_product %></th>
          <th><%= t :sold_quantity %></th>
          <th><%= t :price %></th>
          <th><%= t :total_price %></th>
        </tr>
      </thead>
      <tbody>
        <% @products.each do |product, quantity| %>
          <tr>
            <td><%= picture_for product %></td>
            <td class="element-padding-showorder">
              <%= product.name %>
            </td>
            <td class="element-padding-showorder">
              <%= quantity %>
            </td>
            <td class="element-padding-showorder">
              <%= product.price %>
            </td>
            <td class="element-padding-showorder">
              <%= number_to_currency quantity * product.price %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <div class="text-center"><%= paginate @products %></div>
  </div>
</div>

app/views/admin/statistics/index.xls.erb
<?xml version="1.0"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:o="urn:schemas-microsoft-com:office:office"
  xmlns:x="urn:schemas-microsoft-com:office:excel"
  xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:html="http://www.w3.org/TR/REC-html40">
  <Worksheet ss:Name="Sheet1">
    <Table>
      <Row>
        <Cell><Data ss:Type="String"><%= t :id %></Data></Cell>
        <Cell><Data ss:Type="String"><%= t :name %></Data></Cell>
        <Cell><Data ss:Type="String"><%= t :price %></Data></Cell>
        <Cell><Data ss:Type="String"><%= t :category_id %></Data></Cell>
        <Cell><Data ss:Type="String"><%= t :in_stock %></Data></Cell>
        <Cell><Data ss:Type="String"><%= t :order_number %></Data></Cell>
      </Row>
    <% @products.each do |product,quantity| %>
      <Row>
        <Cell><Data ss:Type="Number"><%= product.id %></Data></Cell>
        <Cell><Data ss:Type="String"><%= product.name %></Data></Cell>
        <Cell><Data ss:Type="Number"><%= product.price %></Data></Cell>
        <Cell><Data ss:Type="Number"><%= product.category_id %></Data></Cell>
        <Cell><Data ss:Type="Number"><%= product.in_stock %></Data></Cell>
        <Cell><Data ss:Type="Number"><%= quantity %></Data></Cell>
      </Row>
    <% end %>
    </Table>
  </Worksheet>
</Workbook>