config/routes.rb
Rails.application.routes.draw do

  get "/home", to: "static_pages#home"
  get "/about", to: "static_pages#about"
  get "/index", to: "static_pages#index"
  root "static_pages#home"

  devise_for :users, controllers: {omniauth_callbacks: "omniauth_callbacks"}
  devise_scope :user do
    match "/sessions/user", to: "devise/sessions#create", via: :post
  end
  resources :category, only: [:index, :show] do
    resources :products, only: [:index, :show]
  end
  resources :products do
    resources :comments
  end
  namespace :admin do
    resources :users
    resources :orders
    resources :categories do
      resources :products do
        collection{post :import}
      end
    end
    resources :statistics, only: [:index]
    resources :suggest_products
  end
  resources :sessions, only: [:index, :create, :update, :destroy]
  resources :view, only: [:index]
  namespace :users do
    resources :orders, only: [:index, :create, :show]
  end
  resources :ratings, only: [:create, :update]
  resources :suggestions
  get "*path", to: "static_pages#home"
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category
  has_many :ratings, dependent: :destroy
  has_many :comments
  has_many :order_details, dependent: :destroy
  has_attached_file :image, styles: {small: Settings.small,
    medium: Settings.medium, large: Settings.large}
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/

  class << self
    def take_hot_product item
      @result = Product.select{|product|
        product.is_hot && product.category_id == item.category_id}.shuffle.first
    end

    def take_relate_product item
      @result = Product.select{|product| product.category_id == item.category_id}
        .shuffle.take Settings.product.take_rand
    end

    def take_random_product
      @result = Product.order("RANDOM()").take Settings.product.take_rand
    end

    def get_product_by_category id, category
      @result = category.products.find_by id: id
    end

    def take_home_product
      @result = Product.select{|product|
      product.is_hot}.shuffle.take Settings.product.take_home
    end

    def search search, category_id
      search ? where("name LIKE '%#{search}%' AND category_id = #{category_id}") :
        where("category_id = #{category_id}")
    end

    def search_home search
      search ? where("name LIKE '%#{search}%'") : all
    end

    def load_product_by_id search, array
      @name_search = search.present? ? search : " "
      Product.where(id: array)
        .select{|product| product.name.include? @name_search}
    end

    def take_distinct_category
      Product.select(:category_id).distinct
    end

    def import file
      spreadsheet = open_spreadsheet file
      header = spreadsheet.row 1
      (2..spreadsheet.last_row).each do |i|
        row = Hash[[header, spreadsheet.row(i)].transpose]
        product = find_by_id(row["id"]) || new
        product.attributes = row.to_hash.slice accessible_attributes
        product.save!
      end
    end

    def accessible_attributes
      ["name", "category_id", "in_stock", "price", "description", "sold_quantity"]
    end

    def open_spreadsheet file
      case File.extname file.original_filename
      when ".csv" then Roo::CSV.new file.path
      when ".xlsx" then Roo::Excelx.new file.path
      else raise "#{file.original_filename}"
      end
    end

    def load_product_statitic
      Product.where("sold_quantity > 0").includes :category
    end

    def to_csv options = {}
      CSV.generate(options) do |csv|
        csv << column_names
        all.each do |product|
          csv << product.attributes.values_at(*column_names)
        end
      end
    end

    def load_product_by_order orders
      products = Array.new
      orders.each do |order_detail|
        if products.present? && order_detail.product_id == products.last.first.id
          products.last[1] += order_detail.quantity
        else
          products.append [order_detail.product, order_detail.quantity]
        end
      end
      return products
    end
  end
end

app/models/supports/product.rb
class Supports::Product
  attr_reader :product

  def initialize product, user
    @product = product
    @user = user
  end

  def relate
    @relate ||= Product.take_relate_product @product
  end

  def hot
    @hot = Product.take_hot_product @product
  end

  def randomizes
    @randomizes = Product.take_random_product
  end

  def rating
    @user.nil? ? nil : Rating.find_by(product_id: @product.id, user_id: @user.id)
  end
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController
  skip_before_action :verify_authenticity_token
  load_and_authorize_resource
  before_action :authenticate_user!, :verify_admin, :load_category
  before_action :load_product, only: [:update, :destroy]

  def index
    @products = Product.search params[:search], @category.id
    @products = Kaminari.paginate_array(@products)
      .page(params[:page]).per Settings.product.per_page
  end

  def show
    @product = Product.get_product_by_category params[:id], @category
    if @product.nil?
      flash[:danger] = t :not_exist_data
      redirect_to home_url
    end
  end

  def new
    @product = Product.new
  end

  def edit
  end

  def create
    @product = @category.products.new product_params
    if @product.save
      flash[:success] = t :create_success
      redirect_to admin_category_products_url category_id: @category.id
    else
      flash[:warning] = t :create_fail
      redirect_to :back
    end
  end

  def update
    if @product.update_attributes product_params
      flash[:success] = t :update_success
      redirect_to admin_category_products_url category_id: @category.id
    else
      flash[:warning] = t :update_fail
      redirect_to :back
    end
  end

  def destroy
    @product.order_details.empty? ? @product.destroy :
      render(status: Settings.error_number)
  end

  def import
    Product.import params[:file]
    redirect_to :back
  end

  private

  def load_product
    @product = Product.find_by id: params[:id]
    if @product.nil?
      flash[:danger] = t :not_exist_data
      redirect_to root_url
    end
  end

  def product_params
    params.require(:product).permit :name, :description, :image, :price, :in_stock
  end
end

app/controllers/product_controller.rb
class ProductController < ApplicationController
  before_action :load_category
  def index
    @list = Product.select{
      |x| x.category_id = @category.id}.take Settings.Product_showed_number
    @products = @list.paginate(page: params[:page],
      per_page: Settings.product_per_page)
  end

  private
  def load_category
    @category = Category.find_by id: params[:category_id]
    if @category.nil?
      flash[:danger] = t :not_exist_data
      redirect_to home_path
    end
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :load_category, only: [:index, :show]
  helper_method :sort_column, :sort_direction

  def index
    @products = Product.search(params[:search], @category.id)
      .order sort_column + " " + sort_direction
    @products = Kaminari.paginate_array(@products)
      .page(params[:page]).per Settings.product.per_page
  end

  def show
    @product = Product.get_product_by_category params[:id], @category
    if @product.nil?
      flash[:danger] = t :not_exist_data
      redirect_to home_path
    else
      @supports = Supports::Product.new @product, current_user
      if session[:viewed].present?
        session[:viewed] = session[:viewed].append @product.id
      else
        session[:viewed] = [@product.id]
      end
      @comments = @product.comments.order created_at: :DESC
    end
  end

  private

  def sort_column
    Product.column_names.include?(params[:sort]) ? params[:sort] : "name"
  end

  def sort_direction
    ["asc", "desc"].include?(params[:direction]) ? params[:direction] : "asc"
  end
end

app/views/products/_product.html.erb
<li>
  <p><%= link_to product.name, "#" %></p>
</li>

app/views/products/_relate_product.html.erb
<div class="container product-border">
  <div class="text-center">
    <h3><%= t :relate_product %></h3>
  </div>
  <div class="row">
    <% @supports.relate.each do |product| %>
      <div class="col-md-2 random-width">
        <%= link_to picture_for(product),
          category_product_path(id: product.id) %>
        <p class="name-product"><%= product.name %></p>
        <p class="price-product">
          <%= product.price %>
          <i class="fa fa-dollar size-icon"></i>
        </p>
      </div>
    <% end %>
  </div>
</div>

app/views/products/_update_delete_form.html.erb
<%= form_for :sessions, url: session_path, method: :patch do |f| %>
  <%= f.hidden_field :product_id, value: @product.id %>
  <%= f.hidden_field :category_id, value: @product.category_id %>
  <%= f.number_field :quantity, min: Settings.product.min_quantity,
    max: @product.in_stock, value: Settings.product.min_quantity,
    class: "form-control text-center" %>
  <%= f.submit t(:update_cart), class: "btn btn-info
    right-text stock-product-show" %>
<% end %>
<%= form_for :sessions, url: session_path(@product.id),
  method: :delete do |f| %>
  <%= f.submit t(:delete_cart), class: "btn btn-danger
    right-text stock-product-show" %>
<% end %>

app/views/products/index.html.erb
<div class="container">
  <h3>
    <%= link_to @category.name, category_products_path(id: @category.id) %>
  </h3>
  <%= form_tag @products_path, method: :get do %>
    <%= hidden_field_tag :direction, params[:direction] %>
    <%= hidden_field_tag :sort, params[:sort] %>
    <p>
      <%= text_field_tag :search, params[:search], class: "form-control" %>
      <%= submit_tag t(:search), name: nil, class: "btn btn-info pull-right" %>
    </p>
  <% end %>
  <p><%= sortable "name" %></p>
  <p><%= sortable "price" %></p>
</div>
<div class="container">
  <div class="row">
    <% @products.each do |product| %>
      <div class="col-md-2 random-width">
        <%= link_to picture_for(product),
          category_product_path(category_id: product.category_id,
          id: product.id) %>
        <p class="name-product"><%= product.name %></p>
        <p class="price-product"><%= product.price %>
          <i class="fa fa-dollar size-icon"></i>
        </p>
      </div>
    <% end %>
    <div class="text-center"><%= paginate @products %></div>
  </div>
</div>

app/views/products/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-4 text-center">
      <div><%= picture_for @product, "detail" %></div>
      <button type="button" class="btn btn-info" data-toggle="collapse"
        data-target="#demo"><%= t :describe %></button>
      <div id="demo" class="collapse">
        <%= @product.description %>
      </div>
    </div>
    <div class="col-md-4 border-product-detail">
      <p class="name-product-detail name-product-show"><%= @product.name %></p>
      <p class="price-product-detail price-product-show"><%= @product.price %>
        <i class="fa fa-dollar size-icon"></i>
      </p>
      <div>
        <p class="product-detail stock-product-show"><%= t :in_stock %></p>
        <p class="product-detail right-text"><%= @product.in_stock %></p>
      </div>
      <p class="product-detail rate-product-show"><%= t :rate %></p>
      <% if @supports.rating.present? %>
        <div class="rating-number-show" id="<%= @supports.rating.id %>">
          <% Settings.rating.number_star.times do |x| %>
            <% if @supports.rating.rate == x+1 %>
              <p class="rating" id="number-rating-select"><%= x+1 %></p>
            <% else %>
              <p class="rating" id="number-rating"><%= x+1 %></p>
            <% end %>
          <% end %>
        </div>
      <% else %>
        <div class="rating-number-show" id="0">
          <% Settings.rating.number_star.times do |x| %>
            <p class="rating" id="number-rating">
              <%= link_to x+1, ratings_path(rate: x+1, product_id: @product.id),
                method: :post %>
            </p>
          <% end %>
        </div>
      <% end %>
      <p><%= @product.rate_average %></p>
      <div class="right-text"><%= social_share_button_tag @product.name %></div>
      <% if validate_product @product.id %>
        <%= form_for :sessions, url: sessions_path do |f| %>
          <%= f.hidden_field :product_id, value: @product.id %>
          <%= f.hidden_field :category_id, value: @product.category_id %>
          <%= f.number_field :quantity, min: Settings.product.min_quantity,
            max: @product.in_stock, value: Settings.product.min_quantity,
            class: "form-control text-center form-number-input" %>
          <%= f.submit t(:cart), class: "btn btn-info
            right-text stock-product-show" %>
        <% end %>
      <% end %>
      <% if session[@product.id].present? %>
        <%= render "update_delete_form" %>
      <% end %>
    </div>
    <div class="col-md-3 col-md-offset-1 border-product-detail">
      <div class="padding-hot">
        <% if @supports.hot.present? %>
          <div class="text-center">
            <h3><%= t :hot %></h3>
          </div>
          <%= link_to picture_for(@supports.hot),
            category_product_path(category_id: @supports.hot.category_id,
            id: @supports.hot.id) %>
          <p class="name-product"><%= @supports.hot.name %></p>
          <p class="price-product"><%= @supports.hot.price %>
            <i class="fa fa-dollar size-icon"></i>
          </p>
        <% end %>
      </div>
    </div>
  </div>
</div>
<div class="container">
  <div class="col-md-9" id="comments">
    <%= render @comments %>
  </div>
  <div class="col-md-9">
    <% if user_signed_in? %>
      <h2><%= t :comment %></h2>
      <%= form_for [@product, @product.comments.new],
        method: :post, remote: true do |f| %>
        <div class="form-group">
          <%= f.text_area :content, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.submit t(:comment), class: "btn btn-primary" %>
        </div>
      <% end %>
    <% else %>
      <%= t :login_comment %>
    <% end %>
  </div>
</div>
<%= render "relate_product" %>